### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by ssaip** [ConnorMulqueen/DiscordBot-ClassicWoWMemes#1]
The bot stopped working, tried re-adding it to our server but it still doesn't respond to #nochanges anymore

**Comment by ConnorMulqueen** [comment]
@ssaip Ah, I'll try to get it back online when I get home from work today! It'll be a good avenue to channel my hype for classic 🙂

**Comment by ConnorMulqueen** [comment]
Okay, changed up the hosting - it's back online!

**Comment by ssaip** [comment]
👍 working again, thank you so much :D
